# Generated by Django 2.0 on 2020-08-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0002_item_barang_kode_akun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_pembelian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=20)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('id_item', models.CharField(default='B2IC', max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('uom', models.CharField(default='Set', max_length=50)),
                ('harga', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('pemasok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_akuntansi.Suplier')),
            ],
        ),
        migrations.AddField(
            model_name='pembelian',
            name='sisa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='sudah_dibayar',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='harga',
            field=models.FloatField(),
        ),
    ]
