# Generated by Django 2.0 on 2020-08-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0004_auto_20200810_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelian',
            name='total',
        ),
    ]
