# Generated by Django 2.0 on 2020-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0006_pembelian_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='total',
            field=models.FloatField(default=''),
        ),
    ]
