# Generated by Django 2.0 on 2020-08-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0007_auto_20200810_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_pembelian',
            name='pemasok',
        ),
        migrations.AddField(
            model_name='pembelian',
            name='id_item',
            field=models.CharField(default='B2IC', max_length=50),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='nota',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='pemasok',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_akuntansi.Suplier'),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='uom',
            field=models.CharField(default='Set', max_length=50),
        ),
        migrations.DeleteModel(
            name='Form_pembelian',
        ),
    ]
