# Generated by Django 2.0 on 2020-08-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0008_auto_20200811_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelian',
            name='unit',
        ),
    ]
