# Generated by Django 2.0 on 2020-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0009_remove_pembelian_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='total',
            field=models.FloatField(),
        ),
    ]
