# Generated by Django 2.0 on 2020-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0010_auto_20200811_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='sisa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Hutang', 'Hutang')], default='Lunas', max_length=50),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='sudah_dibayar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
