# Generated by Django 2.0 on 2020-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0011_auto_20200826_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Hutang', 'Hutang')], default='Hutang', max_length=50),
        ),
    ]
