# Generated by Django 2.0 on 2020-09-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0012_auto_20200826_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Outstanding', 'Outstanding')], default='Outstanding', max_length=50),
        ),
    ]
