# Generated by Django 2.0 on 2020-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akuntansi', '0013_auto_20200907_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Hutang', 'Hutang')], default='Hutang', max_length=50),
        ),
    ]
